### ISSUE TITLE
埋蔵金やスコアの最大値について

### ISSUE THREAD

**Issue by johnnyhibiki** [takashi-chikayama/Software-for-IPSJ-International-AI-Programming-Contest-SamurAI-Coding-2019-2020#11]
表題の件、ゲームルールや予選ルール等に定義されていますでしょうか？ 
signed intの最大値より大きな非負偶数の埋蔵金に設定しゲームを実行すると、その値が -2147483648 となり、不正な状態でゲームが進行するようにみえます。

**Comment by task-h** [comment]
埋蔵金の総量は32bit signed integerで扱える範囲内であると仮定していただいて構いません．本件，classroomとウェブサイトでも通知します．

**Comment by johnnyhibiki** [comment]
ご対応いただきありがとうございます。
アナウンスいただいた内容で問題ないと思われますので、クローズします。
