### ISSUE TITLE
HITACHIのロゴファイルが大文字/小文字を区別しないファイルシステムでコンフリクトする

### ISSUE THREAD

**Issue by hinohi** [takashi-chikayama/Software-for-IPSJ-International-AI-Programming-Contest-SamurAI-Coding-2019-2020#2]
## 状況

`git clone` ときに以下の警告がでる。

```text
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:
  'logos/Hitachi.png'
  'logos/hitachi.png'
```

実際、手元の macOS 環境だと `logos/Hitachi.png` が `logos/hitachi.png` で上書きされてしまう。

実害としては `git status` などで両者のどちらかが常に `modified` として判定されてしまう。

## 対応案

`logos/Hitachi.png` を `logos/hitachi-small.png` などにリネームする。
（`logos/Hitachi.png` が小さい画像 `logos/hitachi.png` が大きい画像なので）

**Comment by takashi-chikayama** [comment]
ご報告ありがとうございます。大文字から始まる Hitachi.png はどこでも使っていないようなので、削除します。
